function [branch, node] = Network_rural_Atlantide(Base, time)

Base.Z = (Base.V^2)/Base.S;

slackV = 1.04;
[branch, P, Q] = Data_reader_rural(Base, time);
branch.num = length(branch.start);
branch.cod = [1:1:branch.num]';
node.num = branch.num + 1;
node.feeder = [0; branch.feeder];
          
%%% Branch impedances; shunt admittances are usually negligible at distribution level, and here they are not considered.          
 
%%% Injection powers for all the nodes, except for the slack bus (node 1).
%%% Negative values are for the power consumption of loads.
%%% Positive values are for the power generated by generators.

node.type = cell(node.num,3);
node.type{1,1} = 'slack';
node.type{1,2} = slackV;    % voltage magnitude value
node.type{1,3} = 0;         % voltage phase angle value
for i = 2:node.num
    node.type{i,1} = 'PQ';
    node.type{i,2} = -P(i-1);
    node.type{i,3} = -Q(i-1);
end

