function [branch, node] = Network_LV_grid(t)

% Base.Z = (Base.V^2)/Base.S;       % Per unit impedance calculation - here it is not used because impedance data were already provided in their per unit value

slackV = 1.00;
branch.start = [1, 2, 3, 4, 5, 3, 7, 7,  7,  7, 10, 10, 13, 11, 15, 15, 17, 18, 19, 20, 21, 22, 23 ,24, 25, 23, 27, 27, 27, 27, 30, 30]';
branch.end =   [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]';
branch.cod =   [1:1:32]';
branch.num = length(branch.cod);
node.num = max(branch.end);
  
%%% Branch impedances; shunt admittances are usually negligible at distribution level, and here they are not considered.
    
R = [0.0004, 0.00108675, 0.0004269375, 0.00087975, 0.0009315, ...
    0.0013584375, 0.0000388125, 0.0006856875, 0.00098325, 0.0007115625, ...
    0.00098325, 0.0007245, 0.000414, 0.000905625, 0.000802125, 0.000336375, ...
    0.0006598125, 0.0005304375, 0.0008150625, 0.000336375, 0.00025875, ...
    0.0004528125, 0.0004269375, 0.00087975, 0.0009315, 0.0013584375, ...
    0.0000388125, 0.0006856875, 0.00098325, 0.0007115625, 0.00098325, 0.0007245]';
X = [0.003172, 0.0004095, 0.000160875, 0.0003315, 0.000351, 0.000511875, ...
    0.000014625, 0.000258375, 0.0003705, 0.000268125, 0.0003705, 0.000273, ...
    0.000156, 0.00034125, 0.00030225, 0.00012675, 0.000248625, 0.000199875, ...
    0.000307125, 0.00012675, 0.0000975, 0.000170625, 0.000160875, 0.0003315, ...
    0.000351, 0.000511875, 0.000014625, 0.000258375, 0.0003705, 0.000268125, ...
    0.0003705, 0.000273]';
      
%%% Injection powers for all the nodes, except for the slack bus (node 1). Values are provided in MW.
%%% Positive values are for the power consumption of loads.
%%% Negative values are for the power generated by generators.

load('loads.mat');
P = - 1.65*S.P(:,t)/1e4;
Q = - 1.65*S.Q(:,t)/1e4;

load('gen.mat');
P = P + S(:,t)/10;


branch.R = R;
branch.X = X;
branch.B = zeros(1,branch.num);

node.type = cell(node.num,3); 
node.type{1,1} = 'slack';
node.type{1,2} = slackV;
node.type{1,3} = 0;
for i = 2:node.num
    node.type{i,1} = 'PQ';
    node.type{i,2} = P(i-1);
    node.type{i,3} = Q(i-1);
end