function [branch, node] = Network_toy_grid()

slackV = 1.025;
branch.start = [1, 2, 2, 3, 5, 6, 4, 8,  9]';
branch.end =   [2, 3, 4, 5, 6, 7, 8, 9, 10]';
branch.cod =   [1:1:length(branch.end)]';
branch.num = length(branch.cod);
node.num = max(branch.end);

branch.R = [0.015, 0.007, 0.006, 0.009, 0.007, 0.006, 0.009, 0.007, 0.006]';
branch.X = [0.012, 0.005, 0.002, 0.006, 0.005, 0.002, 0.006, 0.005, 0.002]';
branch.B = zeros(1,branch.num);
          
%%% Branch impedances; shunt admittances are usually negligible at distribution level, and here they are not considered.          
 
%%% Injection powers for all the nodes, except for the slack bus (node 1).
%%% Negative values are for the power consumption of loads.
%%% Positive values are for the power generated by generators.

P = -[0.2, 0.2, 0.3, -0.4, 0.3, 0.9, 0.2, -0.3, 0.8];
Q = P/2;

node.type = cell(node.num,3);
node.type{1,1} = 'slack';
node.type{1,2} = slackV;    % voltage magnitude value
node.type{1,3} = 0;         % voltage phase angle value
for i = 2:node.num
    node.type{i,1} = 'PQ';
    node.type{i,2} = P(i-1);
    node.type{i,3} = Q(i-1);
end